name: Check Commit Message

on:
  push:
    branches:
      - main
jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[dev]')"
    steps:
      - name: condition 1
        if: "contains(github.event.head_commit.message, 'CONDITION 1 MSG')"
        run: echo "condition 1"
      - name: condition 2
        if: "contains(github.event.head_commit.message, 'CONDITION 2 MSG')"
        run: echo "condition 2"

