name: Check Commit Message

on:
  push:
    branches:
      - main
jobs:
  check-commit-message:
    if: ${{ github.event.head_commit.message }} == *"[dev]"* || ${{ github.event.head_commit.message }} == *"[ken]"*
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message
        run: |
            echo "now using dev action by ${GITHUB_ACTOR}"
