name: Check Commit Message

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:


jobs:
  test-github-action:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: echo input branch name
        run: echo ${{ github.event.inputs.branch }}
      - name: echo branch name
        run: echo ${{ github.ref_name }}
