name: Check Commit Message

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        type: string
  workflow_call:
    inputs:
      branch:
        description: 'Branch to build'  
        required: true
        type: string

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[dev]')"
    steps:
      - name: echo input branch name
        run: echo ${{ github.event.inputs.branch }}
      - name: echo branch name
        run: echo ${{ github.ref_name }}

